<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE ZapfTable [
<!ELEMENT ZapfTable ((glyphInfo*), (namedGroupGroup*), (namedGlyphGroup*), (featureInfo*))>
<!ELEMENT glyphInfo (fontGlyph, (unicodeList?), (universalName?), (appleName?), (adobeName?), (AFIIName?), (unicodeLikeName?), (CIDJapanese?), (CIDTraditionalChinese?), (CIDSimplifiedChinese?), (CIDKorean?), (versionHistoryNote?), (designerShortName?), (designerLongName?), (designerUsageNote?), (designerHistoricalNote?))>
<!ELEMENT namedGlyphGroup ((fontName?), (fontGlyph+))>
<!ELEMENT namedGroupGroup ((fontName?), (namedGlyphGroup+))>
<!ELEMENT featureInfo ((fontGlyph+), (aatFeature*), (otFeatureTag*))>
<!ELEMENT fontGlyph EMPTY>
<!ELEMENT unicodeList (unicode+)>
<!ELEMENT unicode EMPTY>
<!ELEMENT universalName EMPTY>
<!ELEMENT appleName EMPTY>
<!ELEMENT adobeName EMPTY>
<!ELEMENT AFIIName EMPTY>
<!ELEMENT unicodeLikeName EMPTY>
<!ELEMENT CIDJapanese EMPTY>
<!ELEMENT CIDTraditionalChinese EMPTY>
<!ELEMENT CIDSimplifiedChinese EMPTY>
<!ELEMENT CIDKorean EMPTY>
<!ELEMENT versionHistoryNote (fontName)>
<!ELEMENT designerShortName (fontName)>
<!ELEMENT designerLongName (fontName)>
<!ELEMENT designerUsageNote (fontName)>
<!ELEMENT designerHistoricalNote (fontName)>
<!ELEMENT fontName EMPTY>
<!ELEMENT aatFeature EMPTY>
<!ELEMENT otFeatureTag EMPTY>
<!ATTLIST ZapfTable  version CDATA  #REQUIRED >
<!ATTLIST unicode  value    CDATA  #REQUIRED
	charName CDATA  #IMPLIED >
<!ATTLIST featureInfo  context CDATA  #REQUIRED >
<!ATTLIST universalName  value CDATA  #REQUIRED >
<!ATTLIST appleName  value CDATA  #REQUIRED >
<!ATTLIST adobeName  value CDATA  #REQUIRED >
<!ATTLIST AFIIName  value CDATA  #REQUIRED >
<!ATTLIST unicodeLikeName  value CDATA  #REQUIRED >
<!ATTLIST CIDJapanese  value CDATA  #REQUIRED >
<!ATTLIST CIDTraditionalChinese  value CDATA  #REQUIRED >
<!ATTLIST CIDSimplifiedChinese  value CDATA  #REQUIRED >
<!ATTLIST CIDKorean  value CDATA  #REQUIRED >
<!ATTLIST aatFeature  type CDATA  #REQUIRED
			setting CDATA #REQUIRED >
<!ATTLIST otFeatureTag  value CDATA  #REQUIRED >
<!ATTLIST fontGlyph  glyphRefID CDATA  #REQUIRED
	glyphName  CDATA  #IMPLIED >
<!ATTLIST fontName  nameRefID  CDATA  #REQUIRED
	nameString CDATA  #IMPLIED >
<!ATTLIST namedGroupGroup isAltForms CDATA #REQUIRED>
<!ATTLIST namedGlyphGroup isAltForms CDATA #REQUIRED>
]>

<!--

	Data generated 	Thu Aug  7 18:16:08 2014

	Generated by ftxanalyzer, version 213
	55
-->

<ZapfTable version="1.0">
	<glyphInfo>
		<fontGlyph glyphRefID="0" glyphName=".notdef" />
		<unicodeList>
			<unicode value="U+F0000" charName="<Private Use Character U+00000>" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="1" glyphName="NULL" />
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="2" glyphName="CR" />
		<unicodeList>
			<unicode value="U+000D" charName="&lt;control&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="3" glyphName="space" />
		<unicodeList>
			<unicode value="U+0020" charName="SPACE" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="4" glyphName="ink.arrow.down" />
		<unicodeList>
			<unicode value="U+E009" charName="&lt;Private Use Character U+E009&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="5" glyphName="ink.arrow.left" />
		<unicodeList>
			<unicode value="U+E00B" charName="&lt;Private Use Character U+E00B&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="6" glyphName="ink.arrow.right" />
		<unicodeList>
			<unicode value="U+E00A" charName="&lt;Private Use Character U+E00A&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="7" glyphName="ink.arrow.up" />
		<unicodeList>
			<unicode value="U+E008" charName="&lt;Private Use Character U+E008&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="8" glyphName="ink.chevron.down" />
		<unicodeList>
			<unicode value="U+E005" charName="&lt;Private Use Character U+E005&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="9" glyphName="ink.chevron.left" />
		<unicodeList>
			<unicode value="U+E006" charName="&lt;Private Use Character U+E006&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="10" glyphName="ink.chevron.right" />
		<unicodeList>
			<unicode value="U+E007" charName="&lt;Private Use Character U+E007&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="11" glyphName="ink.chevron.up" />
		<unicodeList>
			<unicode value="U+E004" charName="&lt;Private Use Character U+E004&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="12" glyphName="ink.triangle.down" />
		<unicodeList>
			<unicode value="U+E002" charName="&lt;Private Use Character U+E002&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="13" glyphName="ink.triangle.left" />
		<unicodeList>
			<unicode value="U+E003" charName="&lt;Private Use Character U+E003&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="14" glyphName="ink.triangle.right" />
		<unicodeList>
			<unicode value="U+E001" charName="&lt;Private Use Character U+E001&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="15" glyphName="ink.triangle.up" />
		<unicodeList>
			<unicode value="U+E000" charName="&lt;Private Use Character U+E000&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="16" glyphName="ink.triangle.down.circle" />
		<unicodeList>
			<unicode value="U+E00C" charName="&lt;Private Use Character U+E00C&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="17" glyphName="ink.triangle.left.circle" />
		<unicodeList>
			<unicode value="U+E00F" charName="&lt;Private Use Character U+E00F&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="18" glyphName="ink.triangle.right.circle" />
		<unicodeList>
			<unicode value="U+E00E" charName="&lt;Private Use Character U+E00E&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="19" glyphName="ink.triangle.up.circle" />
		<unicodeList>
			<unicode value="U+E00D" charName="&lt;Private Use Character U+E00D&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="20" glyphName="ink.chevron.down.circle" />
		<unicodeList>
			<unicode value="U+E014" charName="&lt;Private Use Character U+E014&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="21" glyphName="ink.chevron.left.circle" />
		<unicodeList>
			<unicode value="U+E016" charName="&lt;Private Use Character U+E016&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="22" glyphName="ink.chevron.right.circle" />
		<unicodeList>
			<unicode value="U+E017" charName="&lt;Private Use Character U+E017&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="23" glyphName="ink.chevron.up.circle" />
		<unicodeList>
			<unicode value="U+E015" charName="&lt;Private Use Character U+E015&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="24" glyphName="ink.triangle.down.circle.o" />
		<unicodeList>
			<unicode value="U+E010" charName="&lt;Private Use Character U+E010&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="25" glyphName="ink.triangle.left.circle.o" />
		<unicodeList>
			<unicode value="U+E012" charName="&lt;Private Use Character U+E012&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="26" glyphName="ink.triangle.right.circle.o" />
		<unicodeList>
			<unicode value="U+E013" charName="&lt;Private Use Character U+E013&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="27" glyphName="ink.triangle.up.circle.o" />
		<unicodeList>
			<unicode value="U+E011" charName="&lt;Private Use Character U+E011&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="28" glyphName="ink.chevron.down.circle.o" />
		<unicodeList>
			<unicode value="U+E018" charName="&lt;Private Use Character U+E018&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="29" glyphName="ink.chevron.left.circle.o" />
		<unicodeList>
			<unicode value="U+E01A" charName="&lt;Private Use Character U+E01A&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="30" glyphName="ink.chevron.right.circle.o" />
		<unicodeList>
			<unicode value="U+E01B" charName="&lt;Private Use Character U+E01B&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="31" glyphName="ink.chevron.up.circle.o" />
		<unicodeList>
			<unicode value="U+E019" charName="&lt;Private Use Character U+E019&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="32" glyphName="ink.empty.circle" />
		<unicodeList>
			<unicode value="U+E021" charName="&lt;Private Use Character U+E021&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="33" glyphName="ink.plus.circle" />
		<unicodeList>
			<unicode value="U+E024" charName="&lt;Private Use Character U+E024&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="34" glyphName="ink.minus.circle" />
		<unicodeList>
			<unicode value="U+E023" charName="&lt;Private Use Character U+E023&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="35" glyphName="ink.checked.circle" />
		<unicodeList>
			<unicode value="U+E022" charName="&lt;Private Use Character U+E022&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="36" glyphName="ink.x.circle" />
		<unicodeList>
			<unicode value="U+E025" charName="&lt;Private Use Character U+E025&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="37" glyphName="ink.empty.circle.o" />
		<unicodeList>
			<unicode value="U+E02B" charName="&lt;Private Use Character U+E02B&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="38" glyphName="ink.plus.circle.o" />
		<unicodeList>
			<unicode value="U+E02D" charName="&lt;Private Use Character U+E02D&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="39" glyphName="ink.minus.circle.o" />
		<unicodeList>
			<unicode value="U+E02C" charName="&lt;Private Use Character U+E02C&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="40" glyphName="ink.checked.circle.o" />
		<unicodeList>
			<unicode value="U+E02E" charName="&lt;Private Use Character U+E02E&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="41" glyphName="ink.x.circle.o" />
		<unicodeList>
			<unicode value="U+E02F" charName="&lt;Private Use Character U+E02F&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="42" glyphName="ink.empty.square" />
		<unicodeList>
			<unicode value="U+E01C" charName="&lt;Private Use Character U+E01C&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="43" glyphName="ink.plus.square" />
		<unicodeList>
			<unicode value="U+E01E" charName="&lt;Private Use Character U+E01E&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="44" glyphName="ink.minus.square" />
		<unicodeList>
			<unicode value="U+E01F" charName="&lt;Private Use Character U+E01F&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="45" glyphName="ink.checked.square" />
		<unicodeList>
			<unicode value="U+E01D" charName="&lt;Private Use Character U+E01D&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="46" glyphName="ink.x.square" />
		<unicodeList>
			<unicode value="U+E020" charName="&lt;Private Use Character U+E020&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="47" glyphName="ink.empty.square.o" />
		<unicodeList>
			<unicode value="U+E026" charName="&lt;Private Use Character U+E026&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="48" glyphName="ink.plus.square.o" />
		<unicodeList>
			<unicode value="U+E027" charName="&lt;Private Use Character U+E027&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="49" glyphName="ink.minus.square.o" />
		<unicodeList>
			<unicode value="U+E028" charName="&lt;Private Use Character U+E028&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="50" glyphName="ink.checked.square.o" />
		<unicodeList>
			<unicode value="U+E029" charName="&lt;Private Use Character U+E029&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="51" glyphName="ink.x.square.o" />
		<unicodeList>
			<unicode value="U+E02A" charName="&lt;Private Use Character U+E02A&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="52" glyphName="ink.calendar" />
		<unicodeList>
			<unicode value="U+E030" charName="&lt;Private Use Character U+E030&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="53" glyphName="ink.calendar.day" />
		<unicodeList>
			<unicode value="U+E032" charName="&lt;Private Use Character U+E032&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="54" glyphName="ink.calendar.day.o" />
		<unicodeList>
			<unicode value="U+E033" charName="&lt;Private Use Character U+E033&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="55" glyphName="ink.calendar.o" />
		<unicodeList>
			<unicode value="U+E031" charName="&lt;Private Use Character U+E031&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="56" glyphName="ink.alarm.clock" />
		<unicodeList>
			<unicode value="U+E038" charName="&lt;Private Use Character U+E038&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="57" glyphName="ink.alarm.clock.o" />
		<unicodeList>
			<unicode value="U+E039" charName="&lt;Private Use Character U+E039&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="58" glyphName="ink.clock" />
		<unicodeList>
			<unicode value="U+E034" charName="&lt;Private Use Character U+E034&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="59" glyphName="ink.clock.o" />
		<unicodeList>
			<unicode value="U+E035" charName="&lt;Private Use Character U+E035&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="60" glyphName="ink.clock.reverse" />
		<unicodeList>
			<unicode value="U+E03A" charName="&lt;Private Use Character U+E03A&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="61" glyphName="ink.stopwatch" />
		<unicodeList>
			<unicode value="U+E036" charName="&lt;Private Use Character U+E036&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="62" glyphName="ink.stopwatch.o" />
		<unicodeList>
			<unicode value="U+E037" charName="&lt;Private Use Character U+E037&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="63" glyphName="ink.dribbble" />
		<unicodeList>
			<unicode value="U+E03C" charName="&lt;Private Use Character U+E03C&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="64" glyphName="ink.facebook" />
		<unicodeList>
			<unicode value="U+E03D" charName="&lt;Private Use Character U+E03D&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="65" glyphName="ink.google.plus" />
		<unicodeList>
			<unicode value="U+E055" charName="&lt;Private Use Character U+E055&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="66" glyphName="ink.linkedin" />
		<unicodeList>
			<unicode value="U+E03B" charName="&lt;Private Use Character U+E03B&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="67" glyphName="ink.twitter" />
		<unicodeList>
			<unicode value="U+E03E" charName="&lt;Private Use Character U+E03E&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="68" glyphName="ink.comment" />
		<unicodeList>
			<unicode value="U+E03F" charName="&lt;Private Use Character U+E03F&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="69" glyphName="ink.comment.o" />
		<unicodeList>
			<unicode value="U+E040" charName="&lt;Private Use Character U+E040&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="70" glyphName="ink.reply" />
		<unicodeList>
			<unicode value="U+E041" charName="&lt;Private Use Character U+E041&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="71" glyphName="ink.reply.o" />
		<unicodeList>
			<unicode value="U+E042" charName="&lt;Private Use Character U+E042&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="72" glyphName="ink.compass" />
		<unicodeList>
			<unicode value="U+E043" charName="&lt;Private Use Character U+E043&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="73" glyphName="ink.compass.o" />
		<unicodeList>
			<unicode value="U+E044" charName="&lt;Private Use Character U+E044&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="74" glyphName="ink.direction" />
		<unicodeList>
			<unicode value="U+E045" charName="&lt;Private Use Character U+E045&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="75" glyphName="ink.direction.o" />
		<unicodeList>
			<unicode value="U+E046" charName="&lt;Private Use Character U+E046&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="76" glyphName="ink.poi" />
		<unicodeList>
			<unicode value="U+E047" charName="&lt;Private Use Character U+E047&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="77" glyphName="ink.poi.o" />
		<unicodeList>
			<unicode value="U+E048" charName="&lt;Private Use Character U+E048&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="78" glyphName="ink.star" />
		<unicodeList>
			<unicode value="U+E049" charName="&lt;Private Use Character U+E049&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="79" glyphName="ink.star.o" />
		<unicodeList>
			<unicode value="U+E04A" charName="&lt;Private Use Character U+E04A&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="80" glyphName="ink.half.star" />
		<unicodeList>
			<unicode value="U+E04B" charName="&lt;Private Use Character U+E04B&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="81" glyphName="ink.half.star.o" />
		<unicodeList>
			<unicode value="U+E04C" charName="&lt;Private Use Character U+E04C&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="82" glyphName="ink.reorder" />
		<unicodeList>
			<unicode value="U+E04D" charName="&lt;Private Use Character U+E04D&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="83" glyphName="ink.tag" />
		<unicodeList>
			<unicode value="U+E051" charName="&lt;Private Use Character U+E051&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="84" glyphName="ink.tag.o" />
		<unicodeList>
			<unicode value="U+E052" charName="&lt;Private Use Character U+E052&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="85" glyphName="ink.ticket" />
		<unicodeList>
			<unicode value="U+E04F" charName="&lt;Private Use Character U+E04F&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="86" glyphName="ink.ticket.o" />
		<unicodeList>
			<unicode value="U+E050" charName="&lt;Private Use Character U+E050&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="87" glyphName="ink.ul" />
		<unicodeList>
			<unicode value="U+E04E" charName="&lt;Private Use Character U+E04E&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="88" glyphName="ink.tasks" />
		<unicodeList>
			<unicode value="U+E054" charName="&lt;Private Use Character U+E054&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="89" glyphName="ink.power.off" />
		<unicodeList>
			<unicode value="U+E056" charName="&lt;Private Use Character U+E056&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="90" glyphName="ink.search" />
		<unicodeList>
			<unicode value="U+E057" charName="&lt;Private Use Character U+E057&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="91" glyphName="ink.mail" />
		<unicodeList>
			<unicode value="U+E058" charName="&lt;Private Use Character U+E058&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="92" glyphName="ink.test.tube" />
		<unicodeList>
			<unicode value="U+E059" charName="&lt;Private Use Character U+E059&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="93" glyphName="ink.thumbs.up" />
		<unicodeList>
			<unicode value="U+E05A" charName="&lt;Private Use Character U+E05A&gt;" />
		</unicodeList>
	</glyphInfo>
	<glyphInfo>
		<fontGlyph glyphRefID="94" glyphName="ink.thumbs.down" />
		<unicodeList>
			<unicode value="U+E05B" charName="&lt;Private Use Character U+E05B&gt;" />
		</unicodeList>
	</glyphInfo>
</ZapfTable>

